// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewArticle() {
  return window['go']['backend']['App']['CreateNewArticle']();
}

export function DeleteArticle(arg1) {
  return window['go']['backend']['App']['DeleteArticle'](arg1);
}

export function GenerateArticle(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GenerateArticle'](arg1, arg2, arg3);
}

export function GenerateOutline(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GenerateOutline'](arg1, arg2, arg3);
}

export function GetAIConfig() {
  return window['go']['backend']['App']['GetAIConfig']();
}

export function GetArticleByUUID(arg1) {
  return window['go']['backend']['App']['GetArticleByUUID'](arg1);
}

export function GetPositioning() {
  return window['go']['backend']['App']['GetPositioning']();
}

export function GetRecentArticles(arg1) {
  return window['go']['backend']['App']['GetRecentArticles'](arg1);
}

export function ReadArticle(arg1) {
  return window['go']['backend']['App']['ReadArticle'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['backend']['App']['SaveAIConfig'](arg1);
}

export function SaveArticle(arg1, arg2) {
  return window['go']['backend']['App']['SaveArticle'](arg1, arg2);
}

export function SaveArticleAs(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SaveArticleAs'](arg1, arg2, arg3);
}

export function SaveArticleWithSmartNaming(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['SaveArticleWithSmartNaming'](arg1, arg2, arg3, arg4);
}

export function SaveFileDialog(arg1) {
  return window['go']['backend']['App']['SaveFileDialog'](arg1);
}

export function SavePositioning(arg1) {
  return window['go']['backend']['App']['SavePositioning'](arg1);
}
