// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateNewArticle():Promise<models.Article>;

export function DeleteArticle(arg1:string):Promise<void>;

export function GenerateArticle(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateOutline(arg1:string,arg2:string,arg3:string):Promise<models.GenerateOutlineResult>;

export function GetAIConfig():Promise<models.AIConfig>;

export function GetArticleByUUID(arg1:string):Promise<models.Article>;

export function GetPositioning():Promise<string>;

export function GetRecentArticles(arg1:number):Promise<Array<models.Article>>;

export function ReadArticle(arg1:string):Promise<models.ReadArticleResponse>;

export function SaveAIConfig(arg1:models.AIConfig):Promise<void>;

export function SaveArticle(arg1:string,arg2:string):Promise<void>;

export function SaveArticleAs(arg1:string,arg2:string,arg3:string):Promise<models.Article>;

export function SaveArticleWithSmartNaming(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<models.Article>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SavePositioning(arg1:string):Promise<void>;
