// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckFileExists(arg1:string):Promise<boolean>;

export function CreateNewArticle():Promise<models.Article>;

export function CreateNewArticleWithContent(arg1:string,arg2:string):Promise<models.Article>;

export function DeleteArticle(arg1:string):Promise<void>;

export function DeleteArticleAndFile(arg1:string):Promise<void>;

export function GetArticleByUUID(arg1:string):Promise<models.Article>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetRecentArticles(arg1:number):Promise<Array<models.Article>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadArticle(arg1:string):Promise<models.ReadArticleResponse>;

export function RenameArticleByTitle(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveArticle(arg1:string,arg2:string):Promise<void>;

export function SaveArticleAs(arg1:string,arg2:string,arg3:string):Promise<models.Article>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function UpdateArticleMeta(arg1:string,arg2:Array<string>):Promise<void>;
