// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateArticle(arg1) {
  return window['go']['main']['App']['CreateArticle'](arg1);
}

export function CreateMaterial(arg1) {
  return window['go']['main']['App']['CreateMaterial'](arg1);
}

export function DeleteArticle(arg1) {
  return window['go']['main']['App']['DeleteArticle'](arg1);
}

export function DeleteMaterial(arg1) {
  return window['go']['main']['App']['DeleteMaterial'](arg1);
}

export function GenerateOutline(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateOutline'](arg1, arg2, arg3);
}

export function GetArticle(arg1) {
  return window['go']['main']['App']['GetArticle'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasConfig() {
  return window['go']['main']['App']['HasConfig']();
}

export function ListArticles() {
  return window['go']['main']['App']['ListArticles']();
}

export function ListMaterials(arg1) {
  return window['go']['main']['App']['ListMaterials'](arg1);
}

export function SaveArticle(arg1) {
  return window['go']['main']['App']['SaveArticle'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StreamWriting(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StreamWriting'](arg1, arg2, arg3, arg4, arg5);
}

export function StreamWritingEvent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StreamWritingEvent'](arg1, arg2, arg3, arg4, arg5);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}
