// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIGenerateTopicsFromHot(arg1, arg2) {
  return window['go']['main']['App']['AIGenerateTopicsFromHot'](arg1, arg2);
}

export function ApproveTopic(arg1) {
  return window['go']['main']['App']['ApproveTopic'](arg1);
}

export function CancelWorkflow(arg1) {
  return window['go']['main']['App']['CancelWorkflow'](arg1);
}

export function CreateArticle(arg1) {
  return window['go']['main']['App']['CreateArticle'](arg1);
}

export function CreateArticleFromTopic(arg1, arg2) {
  return window['go']['main']['App']['CreateArticleFromTopic'](arg1, arg2);
}

export function CreateMaterial(arg1) {
  return window['go']['main']['App']['CreateMaterial'](arg1);
}

export function CreateTopic(arg1) {
  return window['go']['main']['App']['CreateTopic'](arg1);
}

export function CreateWorkflow(arg1) {
  return window['go']['main']['App']['CreateWorkflow'](arg1);
}

export function DeleteArticle(arg1) {
  return window['go']['main']['App']['DeleteArticle'](arg1);
}

export function DeleteMaterial(arg1) {
  return window['go']['main']['App']['DeleteMaterial'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['main']['App']['DeleteTopic'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function FetchAndSaveHotTrends(arg1, arg2) {
  return window['go']['main']['App']['FetchAndSaveHotTrends'](arg1, arg2);
}

export function FetchHotTrendsRealtime(arg1, arg2) {
  return window['go']['main']['App']['FetchHotTrendsRealtime'](arg1, arg2);
}

export function GenerateOutline(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateOutline'](arg1, arg2, arg3);
}

export function GetAgentRegistry() {
  return window['go']['main']['App']['GetAgentRegistry']();
}

export function GetArticle(arg1) {
  return window['go']['main']['App']['GetArticle'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHotPlatforms() {
  return window['go']['main']['App']['GetHotPlatforms']();
}

export function GetHotTrendPlatforms() {
  return window['go']['main']['App']['GetHotTrendPlatforms']();
}

export function GetHotTrends(arg1, arg2) {
  return window['go']['main']['App']['GetHotTrends'](arg1, arg2);
}

export function GetTopic(arg1) {
  return window['go']['main']['App']['GetTopic'](arg1);
}

export function GetWorkflow(arg1) {
  return window['go']['main']['App']['GetWorkflow'](arg1);
}

export function GetWorkflowRun(arg1) {
  return window['go']['main']['App']['GetWorkflowRun'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasConfig() {
  return window['go']['main']['App']['HasConfig']();
}

export function HasEncryptionKey() {
  return window['go']['main']['App']['HasEncryptionKey']();
}

export function InitEncryptionKey() {
  return window['go']['main']['App']['InitEncryptionKey']();
}

export function ListArticles() {
  return window['go']['main']['App']['ListArticles']();
}

export function ListMaterials(arg1) {
  return window['go']['main']['App']['ListMaterials'](arg1);
}

export function ListTopics(arg1, arg2) {
  return window['go']['main']['App']['ListTopics'](arg1, arg2);
}

export function ListWorkflowRuns(arg1) {
  return window['go']['main']['App']['ListWorkflowRuns'](arg1);
}

export function ListWorkflows() {
  return window['go']['main']['App']['ListWorkflows']();
}

export function RejectTopic(arg1) {
  return window['go']['main']['App']['RejectTopic'](arg1);
}

export function SaveArticle(arg1) {
  return window['go']['main']['App']['SaveArticle'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchTopics(arg1) {
  return window['go']['main']['App']['SearchTopics'](arg1);
}

export function StartWorkflow(arg1, arg2) {
  return window['go']['main']['App']['StartWorkflow'](arg1, arg2);
}

export function StreamWriting(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StreamWriting'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StreamWritingEvent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StreamWritingEvent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function UpdateTopic(arg1) {
  return window['go']['main']['App']['UpdateTopic'](arg1);
}

export function UpdateWorkflow(arg1) {
  return window['go']['main']['App']['UpdateWorkflow'](arg1);
}
