// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateArticle(arg1:string):Promise<model.Article>;

export function CreateMaterial(arg1:model.Material):Promise<void>;

export function DeleteArticle(arg1:string):Promise<void>;

export function DeleteMaterial(arg1:string):Promise<void>;

export function GenerateOutline(arg1:string,arg2:string,arg3:string):Promise<Array<model.OutlineNode>>;

export function GetArticle(arg1:string):Promise<model.Article>;

export function GetConfig():Promise<model.Config>;

export function Greet(arg1:string):Promise<string>;

export function HasConfig():Promise<boolean>;

export function ListArticles():Promise<Array<model.Article>>;

export function ListMaterials(arg1:string):Promise<Array<model.Material>>;

export function SaveArticle(arg1:model.Article):Promise<void>;

export function SaveConfig(arg1:model.Config):Promise<void>;

export function StreamWriting(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function StreamWritingEvent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<void>;
