// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AIGenerateTopicsFromHot(arg1:Array<string>,arg2:number):Promise<Array<model.Topic>>;

export function ApproveTopic(arg1:string):Promise<void>;

export function CancelWorkflow(arg1:string):Promise<void>;

export function CreateArticle(arg1:string):Promise<model.Article>;

export function CreateArticleFromTopic(arg1:string,arg2:string):Promise<model.Article>;

export function CreateMaterial(arg1:model.Material):Promise<void>;

export function CreateTopic(arg1:model.Topic):Promise<model.Topic>;

export function CreateWorkflow(arg1:model.Workflow):Promise<model.Workflow>;

export function DeleteArticle(arg1:string):Promise<void>;

export function DeleteMaterial(arg1:string):Promise<void>;

export function DeleteTopic(arg1:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function FetchAndSaveHotTrends(arg1:Array<string>,arg2:number):Promise<Array<model.HotTrend>>;

export function FetchHotTrendsRealtime(arg1:Array<string>,arg2:number):Promise<Array<model.HotTrend>>;

export function GenerateOutline(arg1:string,arg2:string,arg3:string):Promise<Array<model.OutlineNode>>;

export function GetAgentRegistry():Promise<Array<Record<string, any>>>;

export function GetArticle(arg1:string):Promise<model.Article>;

export function GetConfig():Promise<model.Config>;

export function GetHotPlatforms():Promise<Array<string>>;

export function GetHotTrendPlatforms():Promise<Array<string>>;

export function GetHotTrends(arg1:string,arg2:number):Promise<Array<model.HotTrend>>;

export function GetTopic(arg1:string):Promise<model.Topic>;

export function GetWorkflow(arg1:string):Promise<model.Workflow>;

export function GetWorkflowRun(arg1:string):Promise<model.WorkflowRun>;

export function Greet(arg1:string):Promise<string>;

export function HasConfig():Promise<boolean>;

export function HasEncryptionKey():Promise<boolean>;

export function InitEncryptionKey():Promise<void>;

export function ListArticles():Promise<Array<model.Article>>;

export function ListMaterials(arg1:string):Promise<Array<model.Material>>;

export function ListTopics(arg1:string,arg2:number):Promise<Array<model.Topic>>;

export function ListWorkflowRuns(arg1:string):Promise<Array<model.WorkflowRun>>;

export function ListWorkflows():Promise<Array<model.Workflow>>;

export function RejectTopic(arg1:string):Promise<void>;

export function SaveArticle(arg1:model.Article):Promise<void>;

export function SaveConfig(arg1:model.Config):Promise<void>;

export function SearchTopics(arg1:string):Promise<Array<model.Topic>>;

export function StartWorkflow(arg1:string,arg2:Record<string, any>):Promise<model.WorkflowRun>;

export function StreamWriting(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function StreamWritingEvent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateTopic(arg1:model.Topic):Promise<void>;

export function UpdateWorkflow(arg1:model.Workflow):Promise<void>;
